config/routes.rb
DigiQuatics::Application.routes.draw do
  resources :sign_ups

  resources :email_groups

  devise_for :users

  resources :attendance_records
  resources :availabilities
  resources :certifications
  resources :certification_names
  resources :chemical_records
  resources :daily_todos
  resources :help_desks
  resources :packages
  resources :pools
  resources :positions
  resources :preventative_lists
  resources :shift_reports
  resources :shifts
  resources :skill_levels
  resources :slide_inspections
  resources :slide_inspection_tasks
  resources :sub_requests
  resources :time_off_requests

  resources :accounts do
    resources :private_lessons, shallow: true
  end

  resources :locations do
    member do
      get 'pools'
    end
  end

  resources :users do
    member do
      get 'certifications'
    end
  end

  # Default Static Pages
  root 'static_pages#landing'
  match '/privacy', to: 'static_pages#privacy', via: 'get'
  match '/tos', to: 'static_pages#tos', via: 'get'
  match '/team', to: 'static_pages#team', via: 'get'
  match '/signup', to: 'static_pages#signup', via: 'get'

  # Dashboard
  match '/dashboard', to: 'static_pages#dashboard', via: 'get'

  # Admin Dashboard
  match '/admin_dashboard', to: 'accounts#admin_dashboard', via: 'get'

  # Chemicals
  match '/chemicals', to: 'static_pages#chemicals',    via: 'get'
  match '/manage_chemicals', to: 'static_pages#manage_chemicals', via: 'get'
  match '/chemical_record_stats',
        to: 'static_pages#chemical_record_stats',
        via: 'get'
  match '/chemical_record_stats',
        to: 'static_pages#chemical_record_stats',
        via: 'post'

  # Certifications
  match '/certifications_stats',
        to: 'static_pages#certifications_stats',
        via: 'get'

  # Scheduling
  match '/my_schedule', to: 'shifts#my_schedule', via: 'get'

  # Sub Requests
  match '/processed_sub_requests', to: 'sub_requests#processed', via: 'get'
  match '/my_sub_requests', to: 'sub_requests#my_sub_requests', via: 'get'
  match '/admin_sub_requests', to: 'sub_requests#admin_index', via: 'get'

  # Time Off
  match '/archived_time_off_requests',
        to: 'time_off_requests#archived_time_off_requests',
        via: 'get'
  match '/my_time_off_requests',
        to: 'time_off_requests#my_time_off_requests',
        via: 'get'

  # Users
  match '/user_stats', to: 'static_pages#user_stats', via: 'get'
  match '/inactive_index', to: 'users#inactive_index', via: 'get'
  match '/all_users', to: 'users#all_users', via: 'get'

  # Private Lessons
  match '/private_lesson_stats', to: 'static_pages#private_lesson_stats', via: 'get'
  match '/admin_index', to: 'private_lessons#admin_index', via: 'get'
  match '/completed_admin_index', to: 'private_lessons#completed_admin_index', via: 'get'
  match '/my_lessons', to: 'private_lessons#my_lessons', via: 'get'
  match '/thank_you', to: 'private_lessons#thank_you', via: 'get'
  match '/my_lessons', to: 'private_lessons#my_lessons', via: 'get'

  # Help Desk
  match '/closed_index', to: 'help_desks#closed_index', via: 'get'
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  METRICS = { 'Free Chlorine (PPM)' => 'free_chlorine_ppm',
              'Combined Chlorine (PPM)' => 'combined_chlorine_ppm',
              'Total Chlorine (PPM)' => 'total_chlorine_ppm',
              'PH' => 'ph',
              'Alkalinity' => 'alkalinity',
              'Calcium Hardness' => 'calcium_hardness',
              'Air Temp (F)' => 'air_temp',
              'Pool Temp (F)' => 'pool_temp',
              'SI Index' => 'si_index' }

  def dashboard
    Tracker.track(current_user.id, 'View Dashboard')
  end

  def privacy
  end

  def tos
  end

  def landing
    render :index, layout: false
  end

  def signup
    render :signup, layout: false
  end

  def team
    render :team, layout: false
  end

  def chemical_record_stats
    Tracker.track(current_user.id, 'View Chemical Record Stats')
    date_picker
    chemical_stats_table
    chemical_graphs
  end

  def user_stats
    @facade = StaticPagesFacade.new(current_user)
    employee_stat_graphs
  end

  def private_lesson_stats
    @facade = StaticPagesFacade.new(current_user)
    private_lessons_count_graph
  end

  private

  def private_lessons_count_graph
    @private_lessons_graph = LazyHighCharts::HighChart.new('graph') do |f|
      f.legend({layout: 'vertical',
                align: 'right',
                verticalAlign: 'middle',
                borderWidth: 0})
      f.series(name: 'Unclaimed',
               data: unclaimed)
      f.series(name: 'Claimed',
               data: claimed)
      f.title({text: 'Total Private Lessons'})
      f.options[:xAxis] = {plot_bands: 'none',
                           title: {text: 'Location'},
                           categories: Location.where(account_id: current_user.account_id).map { |x| x.name }}
      f.options[:chart][:defaultSeriesType] = 'bar'
      f.plot_options({bar: {stacking: 'normal'}})
    end
  end

  def private_lessons
    PrivateLesson.same_account_as(current_user)
  end

  def unclaimed
     @query = []
    location_query.each do |location|
      @query.push(private_lessons.for_location(location).unclaimed.count)
    end
    @query
  end

  def claimed
    @query = []
    location_query.each do |location|
      @query.push(private_lessons.for_location(location).claimed.count)
    end
    @query
  end

  def chemical_graphs
    temp
    ph
    cl
    alk
    ch
    si
  end

  def date_picker
    start_date
    end_date
    @pool_id = params[:pool_id]
  end

  def start_date
    @start_date = params[:start_date]
    if @start_date
      @start_adj = DateTime.strptime(@start_date, '%Y-%m-%d %H:%M:%S').in_time_zone(Time.zone) + 6.hours
    end
  end

  def end_date
    @end_date = params[:end_date]
    if @end_date
      @end_adj = DateTime.strptime(@end_date, '%Y-%m-%d %H:%M:%S').in_time_zone(Time.zone) + 6.hours
    end
  end

  def chemical_stats_table
    @metrics = METRICS
    @facade = StaticPagesFacade.new(current_user)
  end

  def cl
    @cl = LazyHighCharts::HighChart.new('graph') do |f|
      f.title({text: 'Chlorine Levels'})
      f.legend({layout: 'vertical',
                align: 'right',
                verticalAlign: 'middle',
                borderWidth: 0})
      f.series(name: 'Free',
               data: ChemicalRecord.where(pool_id: @pool_id, created_at: @start_adj..@end_adj).order('created_at asc').map { |x| [x.created_at.strftime('%-m/%-d/%Y @ %I:%M%p'), x.free_chlorine_ppm.to_f] },
               color: '#FFC107')
      f.series(name: 'Combined',
               data: ChemicalRecord.where(pool_id: @pool_id, created_at: @start_adj..@end_adj).order('created_at asc').map { |x| [x.created_at.strftime('%-m/%-d/%Y @ %I:%M%p'), x.combined_chlorine_ppm.to_f] },
               color: '#8BC34A')
      f.series(name: 'Total',
               data: ChemicalRecord.where(pool_id: @pool_id, created_at: @start_adj..@end_adj).order('created_at asc').map { |x| [x.created_at.strftime('%-m/%-d/%Y @ %I:%M%p'), x.total_chlorine_ppm.to_f] },
               color: '#259B24')
      f.xAxis [
        {title: {text: 'Record',
                 margin: 10} }
      ]
      f.yAxis [
        {title: {text: 'Chlorine (ppm)',
                 margin: 10} }
      ]
    end
  end

  def temp
    @temp = LazyHighCharts::HighChart.new('graph') do |f|
      f.title({text: 'Temperature Levels'})
      f.tooltip({valueSuffix: '°F'})
      f.legend({layout: 'vertical',
                align: 'right',
                verticalAlign: 'middle',
                borderWidth: 0})
      f.series(name: 'Air',
               data: ChemicalRecord.where(pool_id: @pool_id, created_at: @start_adj..@end_adj).order('created_at asc').map { |x| [x.created_at.strftime('%-m/%-d/%Y @ %I:%M%p'), x.air_temp.to_f] },
               color: '#3F51B5')
      f.series(name: 'Pool',
               data: ChemicalRecord.where(pool_id: @pool_id, created_at: @start_adj..@end_adj).order('created_at asc').map { |x| [x.created_at.strftime('%-m/%-d/%Y @ %I:%M%p'), x.pool_temp.to_f] },
               color: '#5677FC')
      f.xAxis [
        {title: {text: 'Record',
                 margin: 10} }
      ]
      f.yAxis [
        {title: {text: 'Temperature (°F)',
                 margin: 10} }
      ]
    end
  end

  def ph
    @ph = LazyHighCharts::HighChart.new('graph') do |f|
      f.title({text: 'PH Levels'})
      f.legend({layout: 'vertical',
                align: 'right',
                verticalAlign: 'middle',
                borderWidth: 0})
      f.series(name: 'PH',
               data: ChemicalRecord.where(pool_id: @pool_id, created_at: @start_adj..@end_adj).order('created_at asc').map { |x| [x.created_at.strftime('%-m/%-d/%Y @ %I:%M%p'), x.ph.to_f] },
               color: '#E84E40')
      f.xAxis [
        {title: {text: 'Record',
                 margin: 10} }
      ]
      f.yAxis [
        {title: {text: '(pH)',
                 margin: 10} }
      ]
    end
  end

  def alk
    @alk = LazyHighCharts::HighChart.new('graph') do |f|
      f.title({text: 'Alkalinity Levels'})
      f.legend({layout: 'vertical',
                align: 'right',
                verticalAlign: 'middle',
                borderWidth: 0})
      f.series(name: 'Alkalinity',
               data: ChemicalRecord.where(pool_id: @pool_id, created_at: @start_adj..@end_adj).order('created_at asc').map { |x| [x.created_at.strftime('%-m/%-d/%Y @ %I:%M%p'), x.alkalinity.to_f] },
               color: '#009688')
      f.xAxis [
        {title: {text: 'Record',
                 margin: 10} }
      ]
      f.yAxis [
        {title: {text: 'Alkalinity (ppm)',
                 margin: 10}}
      ]
    end
  end

  def ch
    data = ChemicalRecord.where(pool_id: @pool_id, created_at: @start_adj..@end_adj).order('created_at asc').map { |x| [x.created_at.strftime('%-m/%-d/%Y @ %I:%M%p'), x.calcium_hardness.to_f] }
    data.compact
    @ch = LazyHighCharts::HighChart.new('graph') do |f|
      f.title({text: 'Calcium Hardness Levels'})
      f.legend({layout: 'vertical',
                align: 'right',
                verticalAlign: 'middle',
                borderWidth: 0})
      f.series(name: 'Calcium Hardness',
               data: data,
               color: '#9C27B0')
      f.xAxis [
        {title: {text: 'Record',
                 margin: 10} }
      ]
      f.yAxis [
        {title: {text: 'Calcium Hardness (PPM)',
                 margin: 10}}
      ]
    end
  end

  def si
    @si = LazyHighCharts::HighChart.new('graph') do |f|
      f.title({text: 'SI Index'})
      f.legend({layout: 'vertical',
                align: 'right',
                verticalAlign: 'middle',
                borderWidth: 0})
      f.series(name: 'SI Index',
               data: ChemicalRecord.where(pool_id: @pool_id, created_at: @start_adj..@end_adj).order('created_at asc').map { |x| [x.created_at.strftime('%-m/%-d/%Y @ %I:%M%p'), x.si_index.to_f] },
               color: '#FF5722')
      f.xAxis [
        {title: {text: 'Record',
                 margin: 10} }
      ]
      f.yAxis [
        {title: {text: 'SI Index',
                 margin: 10}}
      ]
    end
  end

  def location_query
    Location.same_account_as(current_user)
  end

  def user_query
    User.same_account_as(current_user)
  end

  def males
     @query = []
    location_query.each do |location|
      @query.push(user_query.for_location(location).female.count)
    end
    @query
  end

  def females
    @query = []
    location_query.each do |location|
      @query.push(user_query.for_location(location).female.count)
    end
    @query
  end

  def admin
    @query = []
    location_query.each do |location|
      @query.push(user_query.for_location(location).admin.count)
    end
    @query
  end

  def non_admin
    @query = []
    location_query.each do |location|
      @query.push(user_query.for_location(location).non_admin.count)
    end
    @query
  end

  def active
    @query = []
    location_query.each do |location|
      @query.push(user_query.for_location(location).active.count)
    end
    @query
  end

  def inactive
    @query = []
    location_query.each do |location|
      @query.push(user_query.for_location(location).inactive.count)
    end
    @query
  end

  def shirt_size(size)
    @query = []
    location_query.each do |location|
      @query.push(user_query.for_location(location).where(shirt_size: size).count)
    end
    @query
  end

  def male_suit(size)
    @query = []
    location_query.each do |location|
      @query.push(user_query.for_location(location).male.where(suit_size: size).count)
    end
    @query
  end

  def one_piece(size)
    @query = []
    location_query.each do |location|
      @query.push(user_query.for_location(location).female.where(femalesuit: size).count)
    end
    @query
  end

  def female_top(size)
    @query = []
    location_query.each do |location|
      @query.push(user_query.for_location(location).female.where(shirt_size: size).count)
    end
    @query
  end

  def female_bottom(size)

app/views/static_pages/dashboard.html.erb
<% provide(:title, 'Dashboard') %>
<div class='hidden-xs'>
<h1 class='cross_platform_header'>DigiQuatics Dashboard</h1>
</div>

<div class='well shadow-effect'>
  <div class='row'>
    <div class='col-md-6'>
      <br>
      <% if current_user.chemical_records_access? || current_user.admin? %>
       <%= link_to new_chemical_record_path,
                   class:'btn btn-default btn-primary btn-lg btn-block' do %>
         <center>
           <i class='fa fa-flask fa-2x'></i>
           <br>
           Chemical Record
         </center>
       <% end %>
      <% end %>
      <%= link_to new_help_desk_path,
                 class:'btn btn-default btn-primary btn-lg btn-block' do %>
       <center>
         <i class='fa fa-wrench fa-2x'></i>
         <br>
         Maintenance Issue
       </center>
      <% end %>
      <%= link_to new_shift_report_path,
                 class:'btn btn-default btn-primary btn-lg btn-block' do %>
       <center>
         <i class='fa fa-clipboard fa-2x'></i>
         <br>
         Shift Report
       </center>
      <% end %>
      <%= link_to new_slide_inspection_path,
                 class:'btn btn-default btn-primary btn-lg btn-block' do %>
       <center>
         <i class='fa fa-pencil-square-o fa-2x'></i>
         <br>
         Slide Inspection
       </center>
      <% end %>
    </div>
    <div class='col-md-6'>
      <div class='dashboard-link'>
        <% if current_user.admin? %>
          <div class='row'>
            <div class='col-md-4'>
              <h3>
              <%= link_to admin_sub_requests_path do %>Admin<br>Sub Requests<br><br><% end %>
              </h3>
              <h1><%= number_admin_sub_requests %></h1>
            </div>
            <div class='col-md-4'>
              <h3>
              <%= link_to time_off_requests_path do %>Time Off<br>Requests<br><br><% end %>
              </h3>
              <h1><%= number_time_off_requests %></h1>
            </div>
            <div class='col-md-4'>
              <h3>
                <%= link_to help_desks_path do %>Open<br>Maintenance<br>Issues</h3><% end %>
              </h3>
              <h1><%= number_open_issues %></h1>
            </div>
            <br>
          </div>
        <% end %>
        <% if !current_user.admin? %>
          <div class='row'>
            <div class='col-md-4'>
              <h3>
              <%= link_to sub_requests_path do %>My Pending<br>Sub Requests<br><br><% end %>
              </h3>
              <h1><%= number_my_sub_requests %></h1>
            </div>
            <div class='col-md-4'>
              <h3>
                <%= link_to account_private_lessons_path(account_id: current_user.account_id) do %>
                  My Private Lesson<br>Requests<br>
                <% end %>
              </h3>
              <h1><%= number_my_private_lessons %></h1>
            </div>
            <div class='col-md-4'></div>
            <br>
          </div>
        <% end %>
        <div class='row'>
          <div class='col-md-4'>
            <h3>
            <%= link_to sub_requests_path do %>Pending<br>Sub Requests<br><br><% end %>
            </h3>
            <h1><%= number_sub_requests %></h1>
          </div>
          <div class='col-md-4'>
            <h3>
              <%= link_to account_private_lessons_path(account_id: current_user.account_id) do %>
                Pending<br>Private Lesson<br>Requests
              <% end %>
            </h3>
            <h1><%= number_private_lessons %></h1>
          </div>
          <div class='col-md-4'></div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DigiQuatics - Web Based Scheduling for Aquatics Management</title>
    <meta name='viewport'
          content='width=device-width, initial-scale=1.0 user-scalable=no'>
    <meta name='description'
          content='Online scheduling and data management for rec centers,
                   YMCAs, country clubs, and HOA pools.'>
    <%= stylesheet_link_tag 'application', media: 'all',
                            'data-turbolinks-track' => true %>
    <%= render 'layouts/google_analytics' %>
  </head>

  <body id='ladningBody'>
    <%= custom_bootstrap_flash %>
    <div>
      <div id='splash_page'>
        <div class='pull-right'>
          <% unless signed_in? %>
            <%= link_to 'Sign In', new_user_session_path,
                        id: 'landing_sign_in_link' %>
          <% else %>
            <%= link_to 'Dashboard', dashboard_path,
                        id: 'landing_sign_in_link' %>
          <% end %>
        </div>
        <br>
        <center>
          <h3><i class='fa fa-tint fa-lg'></i> DigiQuatics</h3>
          <strong id='main-heading'>
            Manage Pools...<br><br>
            Not Paper
          </strong>
          <!-- <h5 id='sub-heading'>
          </h5> -->
        </center>
        <div id='sub-heading2'>
          <%= link_to 'TRY IT FREE FOR 30 DAYS', '#dq_sign_up',
                       class: 'btn btn-default btn-lg btn-outline-cta1',
                       id: 'header-btn' %>
        </div>
      </div>
    </div>

    <%= render 'layouts/landing_nav' %>

    <center>
      <div id='dq_overview' class='mobile_fix'>
        <br><br>
        <p id='overview_content'>
          Online scheduling and data management tool for aquatics departments.
          Save time on scheduling and managing your facility while also
          increasing revenue by managing your private lessons program online.
          Eliminate paperwork and digitize your facility today.
        </p>
        <br><br>
      </div>

      <div id='dq_features'>
        <hr>
        <br><br>
        <strong id='info-header'>FEATURES</strong>
        <br><br><br>
        <div class='row'>
          <div class='col-sm-1'></div>
          <div class='col-sm-2'>
            <div class='blue_icon'>
              <i class='fa fa-flask fa-5x'></i>
            </div>
            <br>
            <h4>Chemical<br>Records</h4>
            <p class='mobile_features_text'>
              Submit pool chemical readings on-the-go. Instantly calculate
              combined chlorine and saturation index (SI) upon submitting
              a chemical record. Receive detailed recomendations based on your
              readings and track trends using our robust analytics platform.
            </p>
          </div>
          <div class='col-sm-2'>
            <div class='blue_icon'>
              <i class='fa fa-users fa-5x'></i>
            </div>
            <br>
            <h4>Employee<br>Management</h4>
            <p class='mobile_features_text'>
              Manage all your staff information in one place: contact
              information, sizing, emergency contacts, notes, and more.
              Track American Red Cross, Ellis and Associates, and other certifications.
              Know when your employees need to renew automatically.
            </p>
          </div>
          <div class='col-sm-2'>
            <div class='blue_icon'>
              <i class='fa fa-calendar fa-5x'></i>
            </div>
            <br>
            <h4>Staff<br>Scheduling</h4>
            <p class='mobile_features_text'>
              Create schedules for your locations and staff and publish online. Designed to
              work with multiple locations. Staff can submit availabilities,
              sub requests and time off requests online.
            </p>
          </div>
          <div class='col-sm-2'>
            <div class='blue_icon'>
              <i class='fa fa-child fa-5x'></i>
            </div>
            <br>
            <h4>Private Lessons<br>Portal</h4>
            <p class='mobile_features_text'>
              Parents can request private lessons online 24/7 (without creating an account).
              The requests instantly push to an online queue system where instructors
              can claim the lessons and get paired up with students.
            </p>
          </div>
          <div class='col-sm-2'>
            <div class='blue_icon'>
              <i class='fa fa-wrench fa-5x'></i>
            </div>
            <br>
            <h4>Maintenance<br>Tracking</h4>
            <p class='mobile_features_text'>
              Issue tracking system allows any staff member to flag issues.
              Upload photos of any problems from your mobile device. Handle and
              manage slide inspections online with instant notifications of
              potential problems.
            </p>
          </div>
          <div class='col-sm-1'></div>
        </div>
        <br><br>
      </div>

      <div id='dq_benefits'>
        <hr>
        <br><br>
        <strong id='info-header'>BENEFITS</strong>
        <br><br>
        <div id='benefit_content'>
          <li>Email and SMS notifications</li>
          <br>
          <li>Designed with mobile in mind</li>
          <br>
          <li>Cloud based data protection</li>
          <br>
          <li>Built in tech support</li>
          <br>
          <li>Robust security</li>
          <br>
          <li>Export your data anytime</li>
        </div>
        <br>
        <br>
      </div>

      <div id='dq_pricing'>
        <hr>
        <br><br>
        <strong id='info-header'>PRICING</strong>
        <br><br>
        <div id='pricing_content'>
        <div>
          <div id='pricing_table'>
            <br>
            <h4>Any Size Organization</h4>
            <br>
            <h5>Request Quote<br><br>
              <%= link_to 'Josh@digiquatics.com',
                          'mailto:Josh@digiquatics.com',
                           id: 'email_link' %>
            </h5>
          </div>
        </div>
        <br><br><br>
        </div>
      </div>

      <div id='dq_sign_up'>
        <hr>
        <br><br>
        <strong id='info-header'>SIGN UP</strong>
        <br><br>
        <p id='mobile-content' class='mobile_features_text'>
          Sign up to gain access to DigiQuatics. Our team will reach out to you
          imediately to onboard your facility and staff onto our platform. We
          do all the heavy lifting so you don't have to. Just send us your
          data!
        </p>
        <br>
        <div class='landing_button_text'>
        <%= link_to 'SIGN UP TODAY FOR FREE TRIAL', signup_path,
                     class: 'btn btn-default btn-lg btn-outline-cta1' %>
        </div>
        <strong>No Credit Card Required</strong>
        <br><br><br>
      </div>

      <div id='dq_demo'>
        <hr>
        <br><br>
        <strong id='info-header'>DEMO</strong>
        <br><br>
        <p id='mobile-content' class='mobile_features_text'>
          Our team would love to demo the app for you anytime. If you are local
          we would love to come meet face to face. Otherwise a virtual meeting
          can be setup easily.
        </p>
        <br><br>
      </div>

      <div id='dq_contact'>
        <hr>
        <br><br>
        <strong id='info-header'>CONTACT</strong>
        <br><br>
          <p id='mobile-content' class='mobile_fix'>
           We're headquartered in Denver, Colorado and would love to meet in
           person if you're local too. Otherwise, you can contact us via phone,
           email, or Twitter
           <a style='color: black;' href='https://twitter.com/DigiQuatics'>
             <b> @DigiQuatics</b>.
           </a>
          </p>
          <div id='contact_link'>
            <a class='btn btn-default btn-lg btn-outline-cta1'
               href='tel:303-921-8628'>
              <i class='fa fa-phone fa-lg'></i>
               (303)-921-8628</a>
              <br><br>
            <a class='btn btn-default btn-lg btn-outline-cta1'
               href='mailto:Josh@digiquatics.com'>
              <i class='fa fa-envelope fa-lg'></i>
               Josh@digiquatics.com</a>
          </div>
          <br><br><br><br>
      </div>

      <div id='social'>
        <br><br>
        <p class='social_icon'>
          <a href='https://twitter.com/DigiQuatics'>
            <i class='fa fa-twitter-square fa-3x'></i>
          </a>
          <a href='https://www.facebook.com/DigiQuatics'>
            <i class='fa fa-facebook-square  fa-3x'></i>
          </a>
          <a href='http://instagram.com/DigiQuatics'>
            <i class='fa fa-instagram fa-3x'></i>
          </a>
        </p>
        <br><br>
      </div>

      <div id='copyright'>
        <br><br>
        <div class='row'>
          <div class='col-md-4'></div> <!-- Placeholder -->
          <div class='col-md-2'>
            <h4 class='whiteText'>Company</h4>
            <p class='footer_text_primary'>
              <a href='/tos'> Terms of Service </a>
              <br>
              <a href='/privacy'> Privacy Policy </a>
            </p>
          </div>
          <div class='col-md-2'>
            <h4 class='whiteText'>About</h4>
              <p class='footer_text_primary'>
              <a href='/team'> The Team </a>
            </p>
          </div>
          <div class='col-md-4'></div> <!-- Placeholder -->
            <br><br><br><br><br><br>
            <p class='whiteText'>
              Made with <i class='fa fa-heart fa-1x' id='heart'></i>
              in Denver, CO
              <%= image_tag('/images/co.png', alt: 'Colorado State Flag') %>
            </p>
            <br>
            <span>&#169; 2013-2014 -</span>
            <a href='http://www.affektive.com'>
              Affketive Software LLC
            </a>
        </div>
        <br><br>
      </div>
    </center>
  </body>
</html>

app/views/static_pages/private_lesson_stats.html.erb
<% provide(:title, 'Private Lesson Statistics') %>
<h1 class='cross_platform_header'>Private Lesson Statistics</h1>

<div class='pull-left'>
  <%= link_to account_private_lessons_path(account_id: current_user.account_id),
      class:'btn btn-default btn-circle' do %>
    <i class='fa fa-arrow-left fa-lg'></i>
  <% end %>
</div>
<br><br><br><br>

<table class='table table-bordered table-white shadow-effect'>
  <tr>
    <th>Metric</th>
    <th>Uncliamed</th>
    <th>Claimed</th>
    <th>Total</th>
  </tr>
  <tr>
    <th>All Locations</th>
    <th><%= @facade.unclaimed_total %></th>
    <th><%= @facade.claimed_total %></th>
    <th><%= @facade.total %></th>
  </tr>
</table>
<br>

<div class='shadow-effect'>
  <%= high_chart('private_lessons_graph', @private_lessons_graph) %>
</div>