config/routes.rb
DigiQuatics::Application.routes.draw do
  resources :sign_ups

  resources :email_groups

  devise_for :users

  resources :attendance_records
  resources :availabilities
  resources :certifications
  resources :certification_names
  resources :chemical_records
  resources :daily_todos
  resources :help_desks
  resources :packages
  resources :pools
  resources :positions
  resources :preventative_lists
  resources :shift_reports
  resources :shifts
  resources :skill_levels
  resources :slide_inspections
  resources :slide_inspection_tasks
  resources :sub_requests
  resources :time_off_requests

  resources :accounts do
    resources :private_lessons, shallow: true
  end

  resources :locations do
    member do
      get 'pools'
    end
  end

  resources :users do
    member do
      get 'certifications'
    end
  end

  # Default Static Pages
  root 'static_pages#landing'
  match '/privacy', to: 'static_pages#privacy', via: 'get'
  match '/tos', to: 'static_pages#tos', via: 'get'
  match '/team', to: 'static_pages#team', via: 'get'
  match '/signup', to: 'static_pages#signup', via: 'get'

  # Dashboard
  match '/dashboard', to: 'static_pages#dashboard', via: 'get'

  # Admin Dashboard
  match '/admin_dashboard', to: 'accounts#admin_dashboard', via: 'get'

  # Chemicals
  match '/chemicals', to: 'static_pages#chemicals',    via: 'get'
  match '/manage_chemicals', to: 'static_pages#manage_chemicals', via: 'get'
  match '/chemical_record_stats',
        to: 'static_pages#chemical_record_stats',
        via: 'get'
  match '/chemical_record_stats',
        to: 'static_pages#chemical_record_stats',
        via: 'post'

  # Certifications
  match '/certifications_stats',
        to: 'static_pages#certifications_stats',
        via: 'get'

  # Scheduling
  match '/my_schedule', to: 'shifts#my_schedule', via: 'get'

  # Sub Requests
  match '/processed_sub_requests', to: 'sub_requests#processed', via: 'get'
  match '/my_sub_requests', to: 'sub_requests#my_sub_requests', via: 'get'
  match '/admin_sub_requests', to: 'sub_requests#admin_index', via: 'get'

  # Time Off
  match '/archived_time_off_requests',
        to: 'time_off_requests#archived_time_off_requests',
        via: 'get'
  match '/my_time_off_requests',
        to: 'time_off_requests#my_time_off_requests',
        via: 'get'

  # Users
  match '/user_stats', to: 'static_pages#user_stats', via: 'get'
  match '/inactive_index', to: 'users#inactive_index', via: 'get'
  match '/all_users', to: 'users#all_users', via: 'get'

  # Private Lessons
  match '/private_lesson_stats', to: 'static_pages#private_lesson_stats', via: 'get'
  match '/admin_index', to: 'private_lessons#admin_index', via: 'get'
  match '/completed_admin_index', to: 'private_lessons#completed_admin_index', via: 'get'
  match '/my_lessons', to: 'private_lessons#my_lessons', via: 'get'
  match '/thank_you', to: 'private_lessons#thank_you', via: 'get'
  match '/my_lessons', to: 'private_lessons#my_lessons', via: 'get'

  # Help Desk
  match '/closed_index', to: 'help_desks#closed_index', via: 'get'
end

app/models/maintenance/shift_report.rb
class ShiftReport < ActiveRecord::Base
  extend ScopeHelper
  include_scopes

  ATTACHED_PATH = ':rails_root/public/system/:attachment/:id/:style/:filename'

  belongs_to :account
  belongs_to :location
  belongs_to :user

  has_attached_file :attachment_front,
                    path: ATTACHED_PATH,
                    url: '/system/:attachment/:id/:style/:filename'

  has_attached_file :attachment_back,
                    path: ATTACHED_PATH,
                    url: '/system/:attachment/:id/:style/:filename'

  validates_presence_of :content, :user_id, :location_id

  comma do
    content
    user_id
    location_id
  end
end

app/controllers/maintenance/shift_reports_controller.rb
class ShiftReportsController < ApplicationController
  before_action :set_shift_report, only: [:show, :edit, :update, :destroy]

  def index
    Tracker.track(current_user.id, 'Shift Reports Index')
    @shift_reports = ShiftReport.joins(:location)
                     .where(locations: { account_id: current_user.account_id })

    respond_to do |format|
      format.html
      format.json
      format.csv do
        render csv: @shift_reports, filename: 'shift_reports'
      end
    end
  end

  def show
    Tracker.track(current_user.id, 'Show Shift Report')
  end

  def new
    @shift_report = ShiftReport.new
  end

  def edit
    Tracker.track(current_user.id, 'Edit Shift Report')
  end

  def create
    Tracker.track(current_user.id, 'Create Shift Report')
    @shift_report = ShiftReport.new(shift_report_params)
    @shift_report.user_id = current_user.id

    message = 'Shift Report was successfully created.'

    handle_action(@shift_report, message, 'success', :new, &:save)
  end

  def update
    Tracker.track(current_user.id, 'Update Shift Report')
    message = 'Shift Report was successfully updated.'

    handle_action(@shift_report, message, 'info', :edit) do |resource|
      resource.update(shift_report_params)
    end
  end

  def destroy
    @shift_report.destroy
    redirect_to shift_reports_url
    flash[:error] = 'Shift Report was successfully deleted.'
  end

  private

  def set_shift_report
    @shift_report = ShiftReport.find(params[:id])
  end

  def shift_report_params
    params.require(:shift_report)
    .permit(:content, :user_id,
            :location_id, :report_filed, :attachment_front, :attachment_back,
            users_attributes: [:id, :first_name, :last_name])
  end

  def handle_action(resource, message, type, page)
    if yield(resource)
      if type == 'success' then
        flash[:success] = message
      else
        flash[:info] = message
      end
      redirect_to resource
    else
      render page
    end
  end
end

app/views/shift_reports/_form.html.erb
<div class='userform well'>
  <%= bootstrap_form_for(@shift_report,
    style: :horizontal, left: 'col-sm-4', right: 'col-sm-8') do |f| %>

    <%= render 'shared/required' %>
    <%= f.select :location_id,
      options_from_collection_for_select(Location.same_account_as(current_user),
                                         :id,
                                         :name, current_user.location_id) %>
    <%= f.text_area :content, label: 'Report *' %>
    <%= f.form_group :report_filed, label: { text: 'Incident / Accident Report Filed' } do %>
      <%= f.check_box :report_filed, label: "" do %>
      <% end %>
    <% end %>
    <%= f.file_field :attachment_front, label: 'Attachment #1' %>
    <%= f.file_field :attachment_back, label: 'Attachment #2' %>
    <% if @shift_report.new_record?() %>
      <button type='submit' class='btn btn-block btn-primary'>
        <i class='fa fa-check'></i> Submit Report
      </button>
    <% else %>
      <button type='submit' class='btn btn-block btn-primary'>
        <i class='fa fa-refresh'></i> Update Report
      </button>
    <% end %>
  <% end %>
</div>
</div>

app/views/shift_reports/edit.html.erb
<% provide(:title, 'Edit Shift Report') %>
<h1>Edit Shift Report</h1>
<%= render partial: 'form' %>

app/views/shift_reports/index.html.erb
<div ng-app='digiquatics'>
  <div ng-controller='ShiftReportsCtrl'>
    <% provide(:title, 'Shift Reports') %>
    <h1 class='cross_platform_header'>Shift Reports</h1>
    <div class='row'>
      <div class='visible-xs'><br></div>
      <%= render 'layouts/location_select' %>
      <dq-search></dq-search>
      <div class='visible-xs'><br></div>
      <div class='col-md-5'></div>
      <div class='col-md-2 pull-right'>
        <div class='pull-right'>
          <%= link_to new_shift_report_path,
              class:'btn btn-primary' do %>
            <i class='fa fa-plus fa-lg'></i>
            Add Report
          <% end %>
        </div>
      </div>
    </div>
    <br><br>
    <div ng-show='(shiftReports
                  | orderBy:order.value:order.reverse
                  | filter:locationFilter
                  | filter:search).length' class='shadow-effect'>
      <table class='table table-bordered table-white'>
        <thead>
          <tr>
            <th>
              <a href='' ng-click="predicate.value = '-location.name'; reverse=!reverse">
              Location</a>
              <span ng-show="thArrow(predicate.value, '-location.name')">
                <dq-arrow></dq-arrow>
              </span>
            </th>
            <th>
              <a href='' ng-click="predicate.value = '-date_stamp'; reverse=!reverse">
              Date</a>
              <span ng-show="thArrow(predicate.value, '-date_stamp')">
                <dq-arrow></dq-arrow>
              </span>
            </th>
            <th>
              <a href='' ng-click="predicate.value = '-user.last_name'; reverse=!reverse">
              Submitted By</a>
              <span ng-show="thArrow(predicate.value, '-user.last_name')">
                <dq-arrow></dq-arrow>
              </span>
            </th>
            <th>
              <a href='' ng-click="predicate.value = '-report_filed'; reverse=!reverse">
              Incident Report</a>
              <span ng-show="thArrow(predicate.value, '-report_filed')">
                <dq-arrow></dq-arrow>
              </span>
            </th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <tr ng-repeat='report in shiftReports
            | orderBy:predicate.value:reverse
            | filter:locationFilter
            | filter:search
            | limitTo:totalDisplayed'>
            <td>{{::report.location.name}}</td>
            <td>
              {{::report.created_at | date:'M/d/yy @ h:mma'}}
            </td>
            <td>{{::report.user.last_name}}, {{::report.user.first_name}} </td>
            <td style='width: 150px;' ng-class='cssClass(report)'>{{::report.report_filed | booleanToWords}}</td>
            <td>
              <%= link_to '/shift_reports/{{::report.id}}' do %>
                <i class='fa fa-external-link fa-lg'></i>
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>
    </div>

    <div ng-show='(shiftReports
                  | orderBy:order.value:order.reverse
                  | filter:locationFilter
                  | filter:search).length > 10'>
      <dq-load-more></dq-load-more>
    </div>
    <div ng-hide='(shiftReports
                  | orderBy:order.value:order.reverse
                  | filter:locationFilter
                  | filter:search).length'>
      <hr/>
      <center>
        <p>
          No shift reports match this search or you have none yet.
            <%= link_to 'Click here to add a shift report.',
                new_shift_report_path %>
        </p>
      </center>
    </div>

  </div>
</div>

app/views/shift_reports/new.html.erb
<% provide(:title, 'New Shift Report') %>
<h1>New Shift Report</h1>
<%= render partial: 'form' %>

app/views/shift_reports/show.html.erb
<% provide(:title, 'Shift Report') %>

<div style='margin-left:0px;'>
  <h1 class='cross_platform_header'>Shift Report</h1>
</div>

<div class='table-width-desktop'>
  <ul class = 'pull-right'>
    <%= link_to edit_shift_report_path(@shift_report),
                class:'btn btn-default btn-primary' do %>
      <i class='fa fa-pencil fa-lg'></i> Edit Report
    <% end %>
  </ul>

  <div class='pull-left'>
    <%= link_to shift_reports_path,
        class:'btn btn-default btn-circle' do %>
      <i class='fa fa-arrow-left fa-lg'></i>
    <% end %>
  </div>
  <br><br><br>

  <table class='table table-clean table-white shadow-effect' >
    <tr>
      <th style='width:25%'> Location </th>
        <td><%= @shift_report.location.name %></td>
    </tr>
    <tr>
      <th> Date Submitted </th>
        <td><%= @shift_report.created_at.strftime('%-m/%-d/%Y @ %I:%M%p') %></td>
    </tr>
    <tr>
      <th> Submitted By </th>
        <td>
          <%= link_to "#{@shift_report.user.last_name},
                       #{@shift_report.user.first_name}",
                       user_path(id: @shift_report.user.id) %>
        </td>
    </tr>
    <tr>
      <th>Incident / Accident Report Filed?</th>
        <td><%= boolean_to_words(@shift_report.report_filed) %></td>
    </tr>
    <tr>
      <th>Attachments</th>
        <td>
          <% if @shift_report.attachment_front? %>
            <%= link_to '', @shift_report.attachment_front.url,
            class: 'glyphicon glyphicon-list-alt' %>
          <% else %>
          <% end %>
          <% if @shift_report.attachment_back? %>
            <%= link_to '', @shift_report.attachment_back.url,
            class: 'glyphicon glyphicon-list-alt' %>
          <% else %>
          <% end %>
        </td>
    </tr>
    <tr>
      <th>Shift Report</th>
        <td><%= @shift_report.content %></td>
    </tr>
  </table>
</div>