config/routes.rb
DigiQuatics::Application.routes.draw do
  resources :sign_ups

  resources :email_groups

  devise_for :users

  resources :attendance_records
  resources :availabilities
  resources :certifications
  resources :certification_names
  resources :chemical_records
  resources :daily_todos
  resources :help_desks
  resources :packages
  resources :pools
  resources :positions
  resources :preventative_lists
  resources :shift_reports
  resources :shifts
  resources :skill_levels
  resources :slide_inspections
  resources :slide_inspection_tasks
  resources :sub_requests
  resources :time_off_requests

  resources :accounts do
    resources :private_lessons, shallow: true
  end

  resources :locations do
    member do
      get 'pools'
    end
  end

  resources :users do
    member do
      get 'certifications'
    end
  end

  # Default Static Pages
  root 'static_pages#landing'
  match '/privacy', to: 'static_pages#privacy', via: 'get'
  match '/tos', to: 'static_pages#tos', via: 'get'
  match '/team', to: 'static_pages#team', via: 'get'
  match '/signup', to: 'static_pages#signup', via: 'get'

  # Dashboard
  match '/dashboard', to: 'static_pages#dashboard', via: 'get'

  # Admin Dashboard
  match '/admin_dashboard', to: 'accounts#admin_dashboard', via: 'get'

  # Chemicals
  match '/chemicals', to: 'static_pages#chemicals',    via: 'get'
  match '/manage_chemicals', to: 'static_pages#manage_chemicals', via: 'get'
  match '/chemical_record_stats',
        to: 'static_pages#chemical_record_stats',
        via: 'get'
  match '/chemical_record_stats',
        to: 'static_pages#chemical_record_stats',
        via: 'post'

  # Certifications
  match '/certifications_stats',
        to: 'static_pages#certifications_stats',
        via: 'get'

  # Scheduling
  match '/my_schedule', to: 'shifts#my_schedule', via: 'get'

  # Sub Requests
  match '/processed_sub_requests', to: 'sub_requests#processed', via: 'get'
  match '/my_sub_requests', to: 'sub_requests#my_sub_requests', via: 'get'
  match '/admin_sub_requests', to: 'sub_requests#admin_index', via: 'get'

  # Time Off
  match '/archived_time_off_requests',
        to: 'time_off_requests#archived_time_off_requests',
        via: 'get'
  match '/my_time_off_requests',
        to: 'time_off_requests#my_time_off_requests',
        via: 'get'

  # Users
  match '/user_stats', to: 'static_pages#user_stats', via: 'get'
  match '/inactive_index', to: 'users#inactive_index', via: 'get'
  match '/all_users', to: 'users#all_users', via: 'get'

  # Private Lessons
  match '/private_lesson_stats', to: 'static_pages#private_lesson_stats', via: 'get'
  match '/admin_index', to: 'private_lessons#admin_index', via: 'get'
  match '/completed_admin_index', to: 'private_lessons#completed_admin_index', via: 'get'
  match '/my_lessons', to: 'private_lessons#my_lessons', via: 'get'
  match '/thank_you', to: 'private_lessons#thank_you', via: 'get'
  match '/my_lessons', to: 'private_lessons#my_lessons', via: 'get'

  # Help Desk
  match '/closed_index', to: 'help_desks#closed_index', via: 'get'
end

app/models/chemical_record.rb
class ChemicalRecord < ActiveRecord::Base
  belongs_to :pool
  belongs_to :location
  belongs_to :user

  validates_presence_of :time_stamp, :user_id, :pool_id, :total_chlorine_ppm,
                        :ph

  comma do
    location name: 'Location'
    pool name: 'Pool'
    free_chlorine_ppm 'Free Cl'
    combined_chlorine_ppm 'Combined Cl'
    total_chlorine_ppm ' Total Cl'
    ph 'PH'
    alkalinity ' Alk'
    calcium_hardness 'CH'
    pool_temp 'Pool(F)'
    air_temp 'Air(F)'
    water_clarity 'Clarity'
    si_index 'SI'
    si_status 'SI Status'
    si_recommendation 'SI Recommendation'
    user last_name: 'Last Name'
    user first_name: 'First Name'
    user phone_number: 'Phone #'
    time_stamp 'Date Submitted'
  end

  def self.same_account_as(user)
    where(pool_id:
      user.account.locations.map(&:pools).reject(&:empty?).flatten.map(&:id))
  end
end

app/controllers/chemical_records_controller.rb
class ChemicalRecordsController < ApplicationController
  include ChemicalRecordsHelper
  before_action :set_chemical_record, only: [:show, :edit, :update, :destroy]
  before_action :admin_user, only: [:edit]
  before_action :chemical_records_access,
                only: [:index, :show, :edit, :update, :destroy, :new]

  def index
    Tracker.track(current_user.id, 'View Chemical Records Index')
    @chemical_records = ChemicalRecord.same_account_as(current_user)

    respond_to do |format|
      format.html
      format.json
      format.csv do
        render csv: @chemical_records, filename: 'chemical_records'
      end
    end
  end

  def show
    Tracker.track(current_user.id, 'Show Chemical Record')
  end

  def new
    @chemical_record = ChemicalRecord.new
  end

  def edit
    Tracker.track(current_user.id, 'Edit Chemical Record')
  end

  def create
    Tracker.track(current_user.id, 'Create Chemical Record')
    @chemical_record = ChemicalRecord.new(chemical_record_params)
    calculations(@chemical_record)
    record_saved?(@chemical_record)
  end

  def update
    Tracker.track(current_user.id, 'Update Chemical Record')
    if @chemical_record.update(chemical_record_params)
      calculations(@chemical_record)
      @chemical_record.save!
      record_updated?(@chemical_record)
    else
      render 'edit'
    end
  end

  def destroy
    @chemical_record.destroy
    redirect_to chemical_records_url
    flash[:error] = 'Chemical Record was successfully deleted.'
  end

  private

  include ApplicationHelper

  def set_chemical_record
    @chemical_record = ChemicalRecord.find(params[:id])
  end

  def chemical_record_params
    params.require(:chemical_record)
    .permit(:free_chlorine_ppm, :total_chlorine_ppm, :chlorine_orp, :ph,
            :alkalinity, :calcium_hardness, :pool_temp, :air_temp, :si_index,
            :time_stamp, :user_id, :pool_id, :water_clarity, :location_id)
  end

  def si_index(record)
    record.si_index =
      si_index_calculator(record.ph,
                          record.pool_temp,
                          record.calcium_hardness,
                          record.alkalinity)
  end

  def chlorine_calculation(record)
    record.combined_chlorine_ppm =
      combined_calculator(record.total_chlorine_ppm,
                          record.free_chlorine_ppm)
  end

  def record_saved?(record)
    if record.save
      flash[:success] = 'Chemical record was successfully created.'
      redirect_to record
    else
      render 'new'
    end
  end

  def record_updated?(record)
    flash[:info] = 'Chemical record was successfully updated.'
    redirect_to @chemical_record
  end

  def calculations(record)
    si_index(record)
    record.si_status = si_calc(record.si_index, :status)
    record.si_recommendation = si_calc(record.si_index, :recommendation)
    record.user_id = current_user.id
    chlorine_calculation(record)
  end

  # if need_email_alert?(@chemical_record)
  #   urgent_email(@chemical_record)
  # end

  # def urgent_email(record)
  #   @account = current_user.account_id
  #   @location_id = record.location_id
  #   @current_user_location_id = current_user.location_id
  #   ChemicalRecordMailer.urgent_email(record, @account, @location_id, @current_user_location_id).deliver
  # end

  # def need_email_alert?(record)
  #   if record.total_chlorine_ppm < 1 || record.total_chlorine_ppm > 5 then
  #     true
  #   elsif record.ph < 6.8 || record.ph > 8.2 then
  #     true
  #   else
  #     false
  #   end
  # end
end

app/helpers/chemical_records_helper.rb
module ChemicalRecordsHelper
  include Math

  SI_CALC_RANGES = {
    [-100, -5] => {
      status: 'Severe Corrosion',
      recommendation: 'Treatment Recommended'
    },
    [-4.99, -2] => {
      status: 'Moderate Corrosion',
      recommendation: 'Treatment May Be Needed'
    },
    [-1.99, -0.5] => {
      status: 'Mild Corrosion',
      recommendation: 'Treatment May Be Needed'
    },
    [-0.49, -0.31] => {
      status: 'Possible Mild Corrosion',
      recommendation: 'Probably No Treatment'
    },
    [-0.3, 0.3] => {
      status: 'Balanced',
      recommendation: 'No Treatment'
    },
    [0.31, 0.5] => {
      status: 'Some Faint Coating',
      recommendation: 'Probably No Treatment'
    },
    [0.51, 1] => {
      status: 'Mild Scale Coating',
      recommendation: 'Treatment May Be Needed'
    },
    [1.01, 2] => {
      status: 'Mild to Moderate Coatings',
      recommendation: 'Treatment May Be Needed'
    },
    [2.01, 3] => {
      status: 'Moderate Scale Forming',
      recommendation: 'Treatment Recommended'
    },
    [3.01, 100] => {
      status: 'Severe Scale Forming',
      recommendation: 'Treatment Recommended'
    }
  }

  def si_index_calculator(ph_reading, pool_temp, calcium_hardness, alkalinity)
    if pool_temp && calcium_hardness && alkalinity
      temp = 0.7571 * log(pool_temp) - 2.6639
      ch   = 0.4341 * log(calcium_hardness) - 0.3926
      ta   = 0.4341 * log(alkalinity) + 0.0074
      @si  = (ph_reading + temp + ch + ta - 12.1).round(2)
    else
      @si = nil
    end
  end

  def si_calc(si_index, option)
    if si_index != nil
      SI_CALC_RANGES.each do |range, message|
        return message[option] if si_index.between?(*range)
      end
    end
  end

  def combined_calculator(total_chlorine, free_chlorine)
    if total_chlorine && free_chlorine
      total_chlorine - free_chlorine
    else
      total_chlorine
    end
  end

  def chemical_records_access
    unless current_user.chemical_records_access?
      flash[:notice] = 'You must have chemical records rights to access this page.'
      redirect_to current_user
    end
  end

end

app/views/chemical_records/_chemicals.html.erb
<div ng-show='(chemicalRecords
              | orderBy:order.value:order.reverse
              | filter:{pool_id: pool_id}
              | filter:{pool: {location_id: location_id}}
              | filter:search).length' class='shadow-effect'>
  <table class='table table-clean table-white'>
    <thead>
      <tr>
        <th>
          <a class='pointer-hand' href=''
             ng-click="predicate.value = 'time_stamp'; reverse=!reverse">
            Time
          </a>
          <span ng-show="thArrow(predicate.value, 'time_stamp')">
            <dq-arrow></dq-arrow>
          </span>
        </th>
        <th class='hidden-xs'>
          <a class='pointer-hand' href=''
             ng-click="predicate.value = '-user.last_name'; reverse=!reverse">
            Submitted By
          </a>
          <span ng-show="thArrow(predicate.value, '-user.last_name')">
            <dq-arrow></dq-arrow>
          </span>
        </th>
        <th class='hidden-xs'>
          <a class='pointer-hand' href=''
             ng-click="predicate.value = '-free_chlorine_ppm'; reverse=!reverse">
            Free Cl
          </a>
          <span ng-show="thArrow(predicate.value, '-free_chlorine_ppm')">
            <dq-arrow></dq-arrow>
          </span>
        </th>
        <th>
          <a class='pointer-hand' href=''
             ng-click="predicate.value = '-total_chlorine_ppm'; reverse=!reverse">
            Total Cl
          </a>
          <span ng-show="thArrow(predicate.value, '-total_chlorine_ppm')">
            <dq-arrow></dq-arrow>
          </span>
        </th>
        <th>
          <a class='pointer-hand' href=''
             ng-click="predicate.value = '-ph'; reverse=!reverse">
            PH
          </a>
          <span ng-show="thArrow(predicate.value, '-ph')">
            <dq-arrow></dq-arrow>
          </span>
        </th>
        <th>
          <a class='pointer-hand' href=''
             ng-click="predicate.value = '-alkalinity'; reverse=!reverse">
            Alk
          </a>
          <span ng-show="thArrow(predicate.value, '-alkalinity')">
            <dq-arrow></dq-arrow>
          </span>
        </th>
        <th>
          <a class='pointer-hand' href=''
             ng-click="predicate.value = '-calcium_hardness'; reverse=!reverse">
            CH
          </a>
          <span ng-show="thArrow(predicate.value, '-calcium_hardness')">
            <dq-arrow></dq-arrow>
          </span>
        </th>
        <th>
          <a class='pointer-hand' href=''
             ng-click="predicate.value = '-pool_temp'; reverse=!reverse">
            Pool(F)
          </a>
          <span ng-show="thArrow(predicate.value, '-pool_temp')">
            <dq-arrow></dq-arrow>
          </span>
        </th>
        <th class='hidden-xs'>
          <a class='pointer-hand' href=''
             ng-click="predicate.value = '-air_temp'; reverse=!reverse">
            Air(F)
          </a>
          <span ng-show="thArrow(predicate.value, '-air_temp')">
            <dq-arrow></dq-arrow>
          </span>
        </th>
        <th class='hidden-xs'>
          <a class='pointer-hand' href=''
             ng-click="predicate.value = '-water_clarity'; reverse=!reverse">
            Water Clarity
          </a>
          <span ng-show="thArrow(predicate.value, '-water_clarity')">
            <dq-arrow></dq-arrow>
          </span>
        </th>
        <th class='hidden-xs'>
          <a class='pointer-hand' href=''
             ng-click="predicate.value = '-si_index'; reverse=!reverse">
            SI Index
          </a>
          <span ng-show="thArrow(predicate.value, '-si_index')">
            <dq-arrow></dq-arrow>
          </span>
        </th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <tr ng-repeat='record in chemicalRecords
        | orderBy:predicate.value:reverse
        | filter:{pool_id: pool_id}
        | filter:{pool: {location_id: location_id}}
        | limitTo:totalDisplayed'>
        <td>
          {{record.time_stamp | date:'M/d/yy @ h:mma'}}
        </td>
        <td class='hidden-xs'>
          <a ng-href='/users/{{record.user.id}}'>
            {{record.user.last_name}}, {{record.user.first_name}}
          </a>
        </td>
        <td class='hidden-xs'>{{record.free_chlorine_ppm}}</td>
        <td>{{record.total_chlorine_ppm}}</td>
        <td>{{record.ph}}</td>
        <td>{{record.alkalinity}}</td>
        <td>{{record.calcium_hardness}}</td>
        <td>{{record.pool_temp}}</td>
        <td class='hidden-xs'>{{record.air_temp}}</td>
        <td class='hidden-xs'>{{record.water_clarity}}</td>
        <td class='hidden-xs'
            ng-class='cssClass(record)'
            tooltip='{{cssClassification(record)}}'
            tooltip-append-to-body='true'>
              {{record.si_index}}
        </td>
        <td>
          <%= link_to '/chemical_records/{{record.id}}' do %>
            <i class='fa fa-external-link fa-lg'></i>
          <% end %>
        </td>
      </tr>
    </tbody>
  </table>
</div>

<div ng-show='(chemicalRecords
              | orderBy:order.value:order.reverse
              | filter:{pool_id: pool_id}
              | filter:{pool: {location_id: location_id}}
              | filter:search).length > 10' >
  <dq-load-more></dq-load-more>
</div>
<div ng-hide='(chemicalRecords
              | orderBy:order.value:order.reverse
              | filter:{pool_id: pool_id}
              | filter:{pool: {location_id: location_id}}
              | filter:search).length' >
  <hr/>
  <center>
    <p>
      No chemical records match this filter or you have none yet.
        <%= link_to 'Click here to add a new record.',
            new_chemical_record_path %>
    </p>
  </center>
</div>

app/views/chemical_records/edit.html.erb
<% provide(:title, 'Edit Chemical Record') %>
<h1>Edit Chemical Record</h1>
<%= render partial: 'form' %>

app/views/chemical_records/index.html.erb
<div ng-app='digiquatics'>
  <div ng-controller='ChemicalRecordsCtrl'>
    <% provide(:title, 'Chemical Records') %>
    <h1 class='cross_platform_header'>Chemical Records</h1>
    <div class='row'>
      <div class='col-md-3'>
        <%= render 'layouts/location_select_chemicals' %>
      </div>
      <div class='col-md-3'>
        <%= render 'layouts/pool_select' %>
      </div>
      <div class='col-md-3'></div>
      <div class='col-md-3 pull-right'>
        <div class='pull-right'>
          <%= link_to new_chemical_record_path,
              class:'btn btn-primary' do %>
            <i class='fa fa-plus fa-lg'></i>
            Add Record
          <% end %>
          <%= link_to chemical_record_stats_path,
              class:'btn btn-success' do %>
            <i class='fa fa-line-chart fa-lg'></i>
            Analytics
          <% end %>
        </div>
      </div>
    </div>
    <div class='row'>
      <div class='col-md-12'>
        <span class='legendRedCell'>
          <i class='fa fa-circle fa-border'></i>
        </span> Danger
        <span class='legendYellowCell'>
          <i class='fa fa-circle fa-border'></i>
        </span> Warning
        <span class='legendGreenCell'>
          <i class='fa fa-circle fa-border'></i>
        </span> Balanced
      </div>
    </div>
    <br>
    <div ng-show='(chemicalRecords
                  | orderBy:order.value:order.reverse
                  | filter:{pool_id: pool_id}
                  | filter:{pool: {location_id: location_id}}
                  | filter:search).length' class='shadow-effect'>
      <table class='table table-clean table-white'>
        <thead>
          <tr>
            <th>
              <a class='pointer-hand' href=''
                 ng-click="predicate.value = 'time_stamp'; reverse=!reverse">
                Time
              </a>
              <span ng-show="thArrow(predicate.value, 'time_stamp')">
                <dq-arrow></dq-arrow>
              </span>
            </th>
            <th class='hidden-xs'>
              <a class='pointer-hand' href=''
                 ng-click="predicate.value = '-user.last_name'; reverse=!reverse">
                Submitted By
              </a>
              <span ng-show="thArrow(predicate.value, '-user.last_name')">
                <dq-arrow></dq-arrow>
              </span>
            </th>
            <th class='hidden-xs'>
              <a class='pointer-hand' href=''
                 ng-click="predicate.value = '-free_chlorine_ppm'; reverse=!reverse">
                Free Cl
              </a>
              <span ng-show="thArrow(predicate.value, '-free_chlorine_ppm')">
                <dq-arrow></dq-arrow>
              </span>
            </th>
            <th>
              <a class='pointer-hand' href=''
                 ng-click="predicate.value = '-total_chlorine_ppm'; reverse=!reverse">
                Total Cl
              </a>
              <span ng-show="thArrow(predicate.value, '-total_chlorine_ppm')">
                <dq-arrow></dq-arrow>
              </span>
            </th>
            <th>
              <a class='pointer-hand' href=''
                 ng-click="predicate.value = '-ph'; reverse=!reverse">
                PH
              </a>
              <span ng-show="thArrow(predicate.value, '-ph')">
                <dq-arrow></dq-arrow>
              </span>
            </th>
            <th>
              <a class='pointer-hand' href=''
                 ng-click="predicate.value = '-alkalinity'; reverse=!reverse">
                Alk
              </a>
              <span ng-show="thArrow(predicate.value, '-alkalinity')">
                <dq-arrow></dq-arrow>
              </span>
            </th>
            <th>
              <a class='pointer-hand' href=''
                 ng-click="predicate.value = '-calcium_hardness'; reverse=!reverse">
                CH
              </a>
              <span ng-show="thArrow(predicate.value, '-calcium_hardness')">
                <dq-arrow></dq-arrow>
              </span>
            </th>
            <th>
              <a class='pointer-hand' href=''
                 ng-click="predicate.value = '-pool_temp'; reverse=!reverse">
                Pool(F)
              </a>
              <span ng-show="thArrow(predicate.value, '-pool_temp')">
                <dq-arrow></dq-arrow>
              </span>
            </th>
            <th class='hidden-xs'>
              <a class='pointer-hand' href=''
                 ng-click="predicate.value = '-air_temp'; reverse=!reverse">
                Air(F)
              </a>
              <span ng-show="thArrow(predicate.value, '-air_temp')">
                <dq-arrow></dq-arrow>
              </span>
            </th>
            <th class='hidden-xs'>
              <a class='pointer-hand' href=''
                 ng-click="predicate.value = '-water_clarity'; reverse=!reverse">
                Water Clarity
              </a>
              <span ng-show="thArrow(predicate.value, '-water_clarity')">
                <dq-arrow></dq-arrow>
              </span>
            </th>
            <th class='hidden-xs'>
              <a class='pointer-hand' href=''
                 ng-click="predicate.value = '-si_index'; reverse=!reverse">
                SI Index
              </a>
              <span ng-show="thArrow(predicate.value, '-si_index')">
                <dq-arrow></dq-arrow>
              </span>
            </th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <tr ng-repeat='record in chemicalRecords
            | orderBy:predicate.value:reverse
            | filter:{pool_id: pool_id}
            | filter:{pool: {location_id: location_id}}
            | limitTo:totalDisplayed'>
            <td>
              {{::record.time_stamp | date:'M/d/yy @ h:mma'}}
            </td>
            <td class='hidden-xs'>
              <a ng-href='/users/{{::record.user.id}}'>
                {{::record.user.last_name}}, {{::record.user.first_name}}
              </a>
            </td>
            <td class='hidden-xs'>{{::record.free_chlorine_ppm}}</td>
            <td>{{::record.total_chlorine_ppm}}</td>
            <td>{{::record.ph}}</td>
            <td>{{::record.alkalinity}}</td>
            <td>{{::record.calcium_hardness}}</td>
            <td>{{::record.pool_temp}}</td>
            <td class='hidden-xs'>{{::record.air_temp}}</td>
            <td class='hidden-xs'>{{::record.water_clarity}}</td>
            <td class='hidden-xs'
                ng-class='cssClass(record)'
                tooltip='{{::cssClassification(record)}}'
                tooltip-append-to-body='true'>
                  {{::record.si_index}}
            </td>
            <td>
              <%= link_to '/chemical_records/{{::record.id}}' do %>
                <i class='fa fa-external-link fa-lg'></i>
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
    <div ng-show='(chemicalRecords
                  | orderBy:order.value:order.reverse
                  | filter:{pool_id: pool_id}
                  | filter:{pool: {location_id: location_id}}
                  | filter:search).length > 10' >
      <dq-load-more></dq-load-more>
    </div>
    <div ng-hide='(chemicalRecords
                  | orderBy:order.value:order.reverse
                  | filter:{pool_id: pool_id}
                  | filter:{pool: {location_id: location_id}}
                  | filter:search).length' >
      <hr/>
      <center>
        <p>
          No chemical records match this filter or you have none yet.
            <%= link_to 'Click here to add a new record.',
                new_chemical_record_path %>
        </p>
      </center>
    </div>
  </div>
</div>

app/views/chemical_records/new.html.erb
<% provide(:title, 'New Chemical Record') %>
<h1>New Chemical Record</h1>
<%= render partial: 'form' %>

app/views/chemical_records/show.html.erb
<% provide(:title, 'Chemical Record') %>
<h1 class='cross_platform_header'>Chemical Record</h1>

<div class='table-width-desktop'>
  <% if current_user.admin? %>
    <ul class='pull-right'>
      <%= link_to edit_chemical_record_path(@chemical_record),
                  class:'btn btn-default btn-primary' do %>
        <i class='fa fa-pencil fa-lg'></i> Edit
      <% end %>
      <%= link_to chemical_record_path(@chemical_record), confirm: 'Are you sure?',
                  method: 'delete', class:'btn btn-default btn-danger' do %>
        <i class='fa fa-trash-o fa-lg'></i> Delete
      <% end %>
    </ul>
  <% end %>

  <div class='pull-left'>
    <%= link_to chemical_records_path,
        class:'btn btn-default btn-circle' do %>
      <i class='fa fa-arrow-left fa-lg'></i>
    <% end %>
  </div>

  <br><br><br>

  <div class='shadow-effect'>
    <table class='table table-bordered table-white'>
      <thead></thead>
      <tbody>
        <tr>
          <th id='fixtablewidth'>Location</th>
          <td><%= Location.find_by_id(@chemical_record.location_id).name %></td>
        </tr>
        <tr>
          <th>Pool</th>
          <td><%= Pool.find_by_id(@chemical_record.pool_id).name %></td>
        </tr>
        <% if @chemical_record.free_chlorine_ppm %>
          <tr>
            <th>Free Chlorine (ppm)</th>
            <td><%= @chemical_record.free_chlorine_ppm %></td>
          </tr>
        <% end %>
        <tr>
          <th>Total Chlorine (ppm)</th>
          <td><%= @chemical_record.total_chlorine_ppm %></td>
        </tr>
        <% if @chemical_record.chlorine_orp %>
          <tr>
            <th> Chlorine(orp)</th>
            <td><%= @chemical_record.chlorine_orp %></td>
          </tr>
        <% end %>
        <tr>
          <th>PH</th>
          <td><%= @chemical_record.ph%> </td>
        </tr>
        <tr>
          <th>Alkalinity</th>
          <td><%= @chemical_record.alkalinity%></td>
        </tr>
        <tr>
          <th>Calcium Hardness</th>
          <td><%= @chemical_record.calcium_hardness%></td>
        </tr>
      <tr>
        <th>Pool Temp</th>
        <td><%= @chemical_record.pool_temp%></td>
      </tr>
      <tr>
        <th>Air Temp</th>
        <td><%= @chemical_record.air_temp%></td>
      </tr>
      <tr>
        <th>SI Index</th>
        <td><%= @chemical_record.si_index%></td>
      </tr>
      <tr>
        <th>SI Status</th>
        <td><%= @chemical_record.si_status %></td>
      </tr>
      <tr>
        <th>SI Recommendation</th>
        <td><%= @chemical_record.si_recommendation %></td>
      </tr>
      <tr>
        <th>Submitted By</th>
          <td>
            <% if @chemical_record.user_id? %>
              <%= link_to "#{@chemical_record.user.last_name},
                           #{@chemical_record.user.first_name}",
                           user_path(id: @chemical_record.user.id) %>
            <% end %>
          </td>
      </tr>
      <tr>
        <th>Phone Number </th>
        <td> <%= phone_number_link(@chemical_record.user.phone_number) %> </td>
      <tr>
        <th>Date Submitted</th>
        <td><%= date_and_time(@chemical_record.time_stamp) %></td>
      </tr>
    </tbody>
    </table>
  </div>
</div>